export const MQTT_CONNECT = "MQTT_CONNECT";
export const MQTT_CONNECTED = "MQTT_CONNECTED";
export const MQTT_DISCONNECT = "MQTT_DISCONNECT";
export const MQTT_DISCONNECTED = "MQTT_DISCONNECTED";
export const MQTT_ONMESSAGE = "MQTT_ONMESSAGE";
export const MQTT_ONSTATUS = "MQTT_ONSTATUS";
export const MQTT_ONPRODUCTION = "MQTT_ONPRODUCTION";
export const MQTT_ONMESSAGEPRODUCTION = "MQTT_ONMESSAGEPRODUCTION";
